version: 0.0
os: linux
files:
  - source: build/libs/guthealth.war
    destination: /var/lib/tomcat10/webapps
file_exists_behavior: OVERWRITE
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu