version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo In the pre_build phase... provide execute permissions on gradlew
      - chmod +x ./gradlew
  build:
    commands:
      - echo In the build phase... build project
      - ./gradlew build --scan
  post_build:
    commands:
      - echo In the post_build phase... nothing to do here
artifacts:
  files:
    - build/libs/guthealth.war
    - appspec.yml