version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo In the pre_build phase... nothing to do here
  build:
    commands:
      - ./gradlew build --scan
  post-build:
    commands:
      - echo In the post_build phase... nothing to do here
  artifacts:
    files:
      - build/libs/guthealth.war
      - appspec.yml